//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BikeApp.Models
{
   
    public class Bike
    {
        [Key]
        public int Bike_Id { get; set; }
        public string Bike_Model { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Status { get; set; }
    }

    public class HiringInfo
    {
        [Key]
        public string startingDate { get; set; }
        public string endingDate { get; set; }
        public int credtCardInfo { get; set; }
    }
}
