//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualRegistration
    {
        public int Id { get; set; }
        public string Name_ { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
    }
}
